# Site settings
title: Logger de pichunchas...
email: me@tiagox.com
description: > # this means to ignore newlines until "baseurl:"
  This's an awesome description for your for this site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tiagox.com" # the base hostname & protocol for your site
twitter_username: tiagox
github_username:  tiagox
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
